project:
  type: website

website:
  title: "IS415 Group 10"
  navbar:
    right:
      - href: index.html
        text: Overview
      - href: gaa-project/proposal.html
        text: Project Proposal
      - href: gaa-project/poster.html
        text: Poster
      - href: gaa-project/user-guide.html
        text: User Guide
      - icon: github
        href: https://github.com/tangxy0321/gga-ThaiRoad
        aria-label: GitHub
        

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

