project:
  type: website

website:
  title: "IS415 Group 10"
  navbar:
    right:
      - href: index.html
        text: Overview
        
      - href: gaa-project/proposal.html
        text: Project Proposal
        
      - text: Prototypes
        menu:
          - text: Data Preparation
            href: gaa-project/data_preparation.html
            
          - text: Exploratory Data Analysis
            href: gaa-project/eda.html
            
          - text: 1st Order Kernel Density Estimation Analysis
            href: gaa-project/<file_name>.html
            
          - text: 2nd Order Kernel Density Estimation Analysis
            href: gaa-project/<file_name>.html
            
          - text: Network-constrained Spatial Point Patterns Analysis
            href: gaa-project/<file_name>.html
        
      - href: gaa-project/poster.html
        text: Poster
        
      - href: gaa-project/user-guide.html
        text: User Guide
        
      - href: gaa-project/Thai_Accidents.html
        text: Dataset Exploration
        
      - href: gaa-project/MoM.html
        text: Minutes of Meeting
        
      - icon: github
        href: https://github.com/tangxy0321/gga-ThaiRoad
        aria-label: GitHub
        

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

